name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  upstream-1:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: upstream-1-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: upstream-1-name-${{ steps.date.outputs.date }}

  upstream-2:
    runs-on: ubuntu-latest
    needs: [upstream-1]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: upstream-2-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: upstream-2-name-${{ steps.date.outputs.date }}

  upstream-3:
    runs-on: ubuntu-latest
    needs: [upstream-2]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: upstream-3-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: upstream-3-name-${{ steps.date.outputs.date }}

  upstream-trigger:
    runs-on: ubuntu-latest
    uses: pshynin/gha-test/.github/workflows/test-reusable-workflow.yml@test4
    needs: [upstream-3]
    steps:
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: upstream-trigger-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: upstream-trigger-name-${{ steps.date.outputs.date }}

