name: Test

on:
  workflow_call:

jobs:
  downstream-1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

  downstream-2:
    runs-on: ubuntu-latest
    needs: [upstream-1]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: downstream-1-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: downstream-1-build-${{ steps.date.outputs.date }}
